Repository Opentek-Org/opentek, pull requests merged in 2022-01, with the labels that each got.

#133 updated style.css
  css/style.css
Labels: bug, SWOC, SWOC21

#137 fixed Slow transition via navbar
  js/custom.js
Labels: SWOC, SWOC21

#135 Added Community Partners section with images
  README.md
Labels: SWOC, SWOC21

#138 Quick links of all the subpages updated as per issue #136
  index.html
  pages/Error.html
  pages/about.html
  pages/event.html
  pages/program.html
  pages/projects.html
  pages/tutorial.html
Labels: SWOC
