Repository Opentek-Org/opentek, pull requests merged in 2023-08, with the labels that each got.

#529 Update index.html and projects.json files.
  data/projects.json
  index.html
Labels: gssoc23, level2

#581 FIxed login,logout and firebase
  index.html
  js/auth.js
Labels: gssoc23, level2, bug

#582 Fixed sharing popup in saved projects and removed unncessary icons
  css/projects.css
  js/saved.js
  pages/projects.html
  pages/saved.html
Labels: gssoc23, level2, bug

#589 Home button Hover #576
  css/bootstrap.min.css
  css/style.css
  index.html
Labels: gssoc23, level2

#593 Added Datascience roadmap
  data/roadmaps.json
  images/roadmaps/DataScience.jpg
  js/roadmap.js
Labels: gssoc23, level1

#588 chore: Added DSA Repo for Preperation
  data/projects.json
Labels: gssoc23, level1, chore

#583 updated the job portal
  css/job.css
Labels: gssoc23, level1

#587 chore: Added Linkedin Clone
  data/projects.json
Labels: gssoc23, level1, chore

#600 Added Backend roadmap
  data/roadmaps.json
  images/roadmaps/Backend.jpg
  js/roadmap.js
Labels: gssoc23, level1

#606 Request for Improving Firestore Data Insertion Script
  data/add.py
Labels: gssoc23, level2

#612 Add 3D Bookmark Animation to Projects Page and Default Checked State for Saved Projects
  css/bookmark.css
  css/projects.css
  js/projects.js
  js/saved.js
  pages/projects.html
  pages/saved.html
Labels: gssoc23, level2

#611 feat: Issue Template and Guideline in Contribute.md ✨
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/other.yml
  CONTRIBUTING.md
Labels: gssoc23, level1

#610 Update README.md
  README.md
Labels: gssoc23, level1

#609 Download button bug
  js/roadmap.js
Labels: gssoc23, level1, bug

#608 docs: enhance documentation by replacing words into attractive badges 📛✨
  README.md
Labels: gssoc23, level1, documentation
