Repository Opentek-Org/opentek, pull requests merged in 2023-07, with the labels that each got.

#387 [ADDED]: Lazy loading
  js/custom.js
Labels: gssoc23, level2

#391 fix : json Syntax error ✔
  data/projects.json
  data/tutorial.json
Labels: gssoc23, level1

#389 Colortheme Issue Fixed
  chatBot/script.js
  css/color-theams.css
Labels: gssoc23, level1

#294 copy right footer
  index.html
Labels: gssoc23, level1, Changes Requested

#402 Added the blog related to the Awesome Open-Source program by Parmesh Bhatt
  data/blogs.json
  images/blogs/Awesome Open-source programs.jpg
Labels: gssoc23, level1

#416 Enhance projects UI
  css/projects.css
Labels: gssoc23, level1

#411 Correct Footer Text
  css/style.css
  index.html
Labels: gssoc23, level1

#413 [Added] - AI Fusion
  data/projects.json
Labels: gssoc23, level1

#422 Enhancement : Latest Project Display First
  js/projects.js
Labels: gssoc23, level1

#430 fix : issue is solve
  index.html
  pages/Error.html
  pages/blog.html
  pages/event.html
  pages/program.html
  pages/projects.html
  pages/tutorial.html
Labels: gssoc23, level1

#433 footer is added
  pages/projects.html
  pages/tutorial.html
Labels: gssoc23, level1

#435 Docker file is added
  Dockerfile
  README.md
Labels: gssoc23, level2, Changes Requested

#438 Add New Video Resources
  data/tutorial.json
Labels: gssoc23, level1

#446 [Added] - Tic-Tac-Toe
  data/projects.json
Labels: gssoc23, level1

#451 Updated Discord Banner
  css/style.css
  images/cap.png
  index.html
Labels: gssoc23, level1

#410 Fixed Navbar issue for all pages
  css/style.css
Labels: gssoc23, level1, doubt by admin

#456 Update tutorial.json
  data/tutorial.json
Labels: gssoc23, level1, Changes Requested

#444 Added Testimonial Page and Form
  .gitignore
  css/style.css
  index.html
  paste.js
  server/app.js
  server/package-lock.json
  server/package.json
Labels: gssoc23, level3

#460 Created Json Checker GitHub Workflow ✔
  .github/workflows/json-check.yml
Labels: gssoc23, level2

#450 Updated Footer alignment
  css/style.css
  index.html
Labels: gssoc23, level1, Changes Requested

#470 Improved the setting icon of the navbar
  css/responsive.css
  css/style.css
Labels: gssoc23, level1

#467 Update projects.json
  data/projects.json
Labels: gssoc23, level1

#480 Modify the feature issues template
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc23, level1

#484 Fixing Size Issues of AI Chatbot in OpenTek
  index.html
Labels: gssoc23, level1

#476 redirecting home fixed
  pages/jobs.html
Labels: gssoc23, level1

#492 Added Delete Testimonial Routes for Admin
  server/app.js
  server/package-lock.json
  server/package.json
  server/views/index.ejs
Labels: gssoc23, level3

#493 Add no projects available card
  css/projects.css
  js/projects.js
Labels: gssoc23, level1

#491 Fixed broken link
  index.html
Labels: gssoc23, level1

#500 Update index.html
  index.html
Labels: gssoc23, level2

#503 feat: created issue template for project addition.
  .github/ISSUE_TEMPLATE/Project.yml
Labels: gssoc23, level2

#508 Implemented Error handling
  server/app.js
  server/errors.js
Labels: gssoc23, level2

#515 feat: made social anchors accessible ✨
  index.html
Labels: gssoc23, level1

#514 Added Essentia: a skincare products website
  data/projects.json
Labels: gssoc23, level1

#520 docs: update dependabot workflow
  .github/dependabot.yml
Labels: gssoc23, level1

#521 chore: update .gitignore
  .gitignore
Labels: gssoc23, level1

#522 docs: add workflow to assign PR to its author
  .github/workflows/author-assign-pr.yml
Labels: gssoc23, level1

#523 docs: update issue forms with proper checklist
  .github/ISSUE_TEMPLATE/Project.yml
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc23, level2

#530 Refactoring index.html, about.css, and Adding Startupimage.js
  css/about.css
  index.html
  js/Startupimage.js
  js/ratingError.js
  js/urlPattern.js
Labels: gssoc23, level2

#519 added firebase
  index.html
  js/auth.js
  js/projects.js
  pages/projects.html
Labels: gssoc23, level3

#533 Automated Changelog Generation with Conventional Commit ⚡
  .github/workflows/Changelog.yml
  package.json
Labels: gssoc23, level1

#534 Save
  js/saved.js
  pages/saved.html
Labels: gssoc23, level1

#538 Setup ESLint, Commitlint, and Prettier for Codebase 🚀
  .eslintrc
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .prettierrc
  commitlint.config.js
  package-lock.json
  package.json
Labels: gssoc23, level3

#524 docs: workflow to add labels after analyzing titles of PR
  .github/labeler-config.yml
  .github/workflows/add-pr-labels.yml
Labels: gssoc23, level2, doubt by admin

#541 Removed the breaked img form Tutorial Cards
  css/style.css
Labels: gssoc23, level1

#542 updated readme
  README.md
Labels: gssoc23, level1

#544 Replaced Alerts with Toast Notifications
  js/projects.js
  pages/projects.html
Labels: gssoc23, level1

#549 Under tutorial video section harikant singh link was not working solv…
  data/tutorial.json
Labels: gssoc23, level1

#548 Add Share Button with Various Social Media Icons and Copy Button
  css/projects.css
  js/projects.js
  pages/projects.html
Labels: gssoc23, level2

#546 Read more Functionality
  css/style.css
  js/tutorial.js
  pages/tutorial.html
Labels: gssoc23, level2

#551 Added two video under Tutorial page
  data/tutorial.json
Labels: gssoc23, level1

#555 Road maps
  css/roadmaps.css
  data/roadmaps.json
  images/roadmaps/MERNStackDev.jpg
  images/roadmaps/frontenddev.jpg
  index.html
  js/roadmap.js
  pages/projects.html
  pages/roadmap.html
Labels: level2

#568 fix: Updated Social Links related Bugs/Issues in Respective HTML Files and Added ARIA attributes to Form Section in index.html File
  index.html
  pages/Error.html
  pages/about.html
  pages/blog.html
  pages/event.html
  pages/jobs.html
  pages/program.html
  pages/projects.html
  pages/roadmap.html
  pages/saved.html
  pages/tutorial.html
Labels: gssoc23, level2, bug
