Repository Opentek-Org/opentek, pull requests merged in 2023-06, with the labels that each got.

#233 added transition effects in feature section
  css/style.css
  index.html
Labels: gssoc23, level1

#231 Fixed Minor Semantic Errors
  index.html
Labels: gssoc23, level1

#208 Update README.md
  README.md
Labels: gssoc23, level1

#246 added Seamless UI and Spectrum UI
  data/projects.json
Labels: gssoc23, level1

#248 Added Projects to Navbar in Home
  index.html
Labels: gssoc23, level1

#254 Refactor: restructure projects data
  data/projects.json
  js/projects.js
Labels: gssoc23, level2

#275 Removing Bug from Projects Page
  css/projects.css
  js/projects.js
Labels: gssoc23, level2

#273 Fix: remove target attribute from nav link
  index.html
  pages/Error.html
  pages/about.html
  pages/blog.html
  pages/event.html
  pages/program.html
  pages/projects.html
  pages/tutorial.html
Labels: gssoc23, level1

#274 Added Color Theams and also improve the buttons in About part of home Page
  css/about.css
  css/blogs.css
  css/color-theams.css
  css/projects.css
  css/responsive.css
  css/slick.css
  css/style.css
  index.html
  js/color-theam.js
  pages/Error.html
  pages/about.html
  pages/blog.html
  pages/event.html
  pages/program.html
  pages/projects.html
  pages/tutorial.html
Labels: gssoc23, level3

#283 Update README.md
  README.md
Labels: gssoc23, level1

#290 Fixed the navbar at the top
  css/style.css
Labels: gssoc23, level1

#304 [Feature Added] Show projects without selecting domain
  css/projects.css
  js/projects.js
Labels: gssoc23, level1

#303 Update style.css for footer-social
  css/style.css
Labels: gssoc23, level1

#326 Added dependabot.yml file
  .github/dependabot.yml
Labels: gssoc23, level1

#325 Project Card UI Improvement
  css/projects.css
  js/projects.js
Labels: gssoc23, level2

#322 discord link is now clickable(Level1)
  css/style.css
Labels: gssoc23, level1

#319 Added a Project Foodies - The Food Hub
  data/projects.json
Labels: gssoc23, level1

#344 Technode Project has been added to the list of ongoing projects.
  data/projects.json
Labels: gssoc23, level1

#347 Fix Typo
  pages/about.html
Labels: gssoc23, level1

#351 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: gssoc23, level1

#281 Added transition effects in the about section
  index.html
Labels: gssoc23, level1, Changes Requested

#320 Changed style for "Repo URL" button
  css/projects.css
  css/style.css
  index.html
  js/color-theam.js
  js/projects.js
  pages/Error.html
  pages/about.html
  pages/blog.html
  pages/event.html
  pages/program.html
  pages/projects.html
  pages/tutorial.html
Labels: gssoc23, level1, Changes Requested

#355 Added the video tutorial how to find the open-source project by Parmesh Bhatt
  data/tutorial.json
Labels: gssoc23, level1

#353 Added the Cloud Computing project by Parmesh Bhatt
  data/projects.json
Labels: gssoc23, level1

#374 Added `openAI-GPT` chat bot
  chatBot/script.js
  chatBot/style.css
  index.html
Labels: gssoc23, level2

#376 Fixed Navbar after Login Issue
  chatBot/script.js
  css/style.css
Labels: gssoc23, level1
